### PR TITLE
Align CDDL between appendix and body

### PR DESCRIPTION
**Pull request by dthaler**
This fixes various contradictions where the CDDL snippets in the body and the complete CDDL at the end did not match.

Addresses #262

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
@kentakayama please review

**Comment by kentakayama** [comment]
Using SUIT_Envelope or SUIT_Envelope_Tagged is still controversial.
Others look good.

**Comment by dthaler** [comment]
Using SUIT_Envelope or SUIT_Envelope_Tagged is still controversial is a separate issue.  This PR does not change anything normative there, it just updates the informative section to match the existing normative section.

**Review by mingpeiwk — APPROVED** [review]
The changes look good to me.

In reading description of each field in the query-request of Section 4.2, supported-freshness-mechanisms isn't introduced next to that for "token" in the order in the message CDDL itself. This is a different issue and assume it may have commented in the past why we chose that way out of order. The other messages follow an order of field appearance in a message such as err_msg where err_code is introduced the last as its position being the last.

**Comment by mingpeiwk** [comment]
BTW, I saw this error when I used cddl validator to validate this CDDL file. It says:

> $ podman run -it -v $PWD:/tmp -w /tmp --rm ghcr.io/anweiss/cddl-cli:latest compile-cddl --cddl draft-ietf-teep-protocol.cddl 
> error: parser errors
>     ┌─ input:19:1
>     │
>  19 │ $teep-type = uint .size 1
>     │ ^^^^^^^^^^^^ all plugs for type socket names must be augmentations using '/='

I checked RFC8610, it does say the following:

> As a convention, all definitions (plugs) for socket names must be
>    augmentations, i.e., they must be using "/="
> 

So I think we may need to change the definition above to:

$teep-type /= uint .size 1

**Review by mingpeiwk — COMMENTED** [review]
Please see my comments on the CDDL validation error.

**Comment by kentakayama** [comment]
> Using SUIT_Envelope or SUIT_Envelope_Tagged is still controversial is a separate issue.

Exactly. It was my fault changing this line in #248 .
This PR should be merged to revert it.

**Comment by mcd500** [comment]
@kentakayama @dthaler 
How about merging this PR and then if we have a conclusion on using the tag on SUIT manifest, then creating another PR at that time.

**Pull request merged**
