### PR TITLE
Replace tc.org with example.org

### PR DESCRIPTION
**Pull request by dthaler**
And wordsmithing in various places

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
@mcd500 The cbor hex also needs to be updated based on these changes, Akira can you do that?  I'm not sure which tool you're using.  cbor.me doesn't seem to deal with embedded CBOR from what I can tell.

**Comment by mcd500** [comment]
@dthaler Thanks, I will check updating cbor hex from changing tc.org to example.org. Might take some time. I am working on the implementation as a highest priority.

**Comment by mcd500** [comment]
Merging this first, fixes for cbor hex comes later.

**Comment by kentakayama** [comment]
@mcd500 @dthaler 
I created PR #177 which solves this issue.

**Pull request merged**
