### PR TITLE
Use SUIT_Component_Identifier as the TAID

### PR DESCRIPTION
**Pull request by dthaler**
Per IETF 109 meeting

Addresses issue #70

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
@mcd500 @bremoran please review

**Comment by mcd500** [comment]
after today's discussion, it might be good to change some of the places from `:` to `=>` at the same time.

**Comment by dthaler** [comment]
> after today's discussion, it might be good to change some of the places from `:` to `=>` at the same time.

@mcd500 done.  Please check.

**Comment by mcd500** [comment]
Thanks, merging

**Pull request merged**
