### PR TITLE
Add SUIT manifest examples

### PR DESCRIPTION
**Pull request by dthaler**
The install example should match Brendan's IETF 111 [slides](https://datatracker.ietf.org/meeting/111/materials/slides-111-teep-sessa-teep-manifest-00)
The delete example was from Brendan's email.

Addresses issue #41

### CODE REVIEW

**Comment by dthaler** [comment]
@bremoran please check for errors

**Comment by mcd500** [comment]
I am reviewing the suit manifest in this PR for https://github.com/ietf-teep/teep-protocol/issues/158.
Wondering changing the uri in the manifest to be at tc server's domain, to make it easier to understand since the manifest is signed by tc developer.

Mentioning it is tc developer have signed it and tc developer is placing the config.json on the server.
```
The TA developer places personalization data for the device on an
HTTPS server and puts the URI in the TA manifest. 
```

This is the description of the uri which using tam's domain and not the tc developer's domain.
```
      / uri / 21:
        'http://tam.teep.example/config.json',
      },
```

**Comment by mcd500** [comment]
The following portion of 'components' is directly following after the 'dependencies' in this format, which may work, however, it might be good to follow the CDDL description to be the  'components' inside 'suit-common' after the 'dependencies'.

```
    / dependencies / 1:[
      {
        / dependency-digest / 1:[
        / algorithm-id / -16 / "sha256" /,
        / digest-bytes / h'd6c1fc7200483092e2db59d4907f9b15'
                         h'05cb3af2795cf78f7ae3d88166fdf743'
        ]
      }
    ],
    / components / 2:[
      ["OP-TEE","RPMB","config.json"]
    ],
```

I am revising the suit manifest formats at https://github.com/ietf-teep/teep-protocol/issues/158 until the formats become concrete.

**Comment by mcd500** [comment]
@dthaler Can we close this PR at now until we finish finalizing the suit manifest formats at https://github.com/ietf-teep/teep-protocol/issues/158?

**Comment by dthaler** [comment]
> @dthaler Can we close this PR at now until we finish finalizing the suit manifest formats at #158?

Since Brendan did the examples, I'd prefer to merge them and then update later as needed.

**Comment by mcd500** [comment]
@dthaler Sure, no problem, merging.

**Pull request merged**
