### PR TITLE
SUIT manifest processing errors

### PR DESCRIPTION
**Pull request by dthaler**
Addresses #52

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by hannestschofenig** [comment]
There is only one issue with the PR, namely the use of the "SUIT_Record" structure. I noticed that this structure is used in Section 8.7.4 of the SUIT manifest draft but it is not used in the CDDL. I discussed this with Brendan and he told me that an update is in progress to fix this inconsistency. 

As soon as the draft update is available, I will update the PR with the correct fieldname

**Comment by dthaler** [comment]
> There is only one issue with the PR, namely the use of the "SUIT_Record" structure. I noticed that this structure is used in Section 8.7.4 of the SUIT manifest draft but it is not used in the CDDL. I discussed this with Brendan and he told me that an update is in progress to fix this inconsistency.
> 
> As soon as the draft update is available, I will update the PR with the correct fieldname

I already had an email exchange with Brendan too, asking if there is a new draft yet since the SUIT 108 agreement was to put it in a separate draft.  Brendan indicated he'd try to have something within a week.

**Comment by dthaler** [comment]
https://tools.ietf.org/html/draft-moran-suit-report-00 is now posted and I've updated this PR to reference it instead.

@hannestschofenig does this look ok now?

**Comment by hannestschofenig** [comment]
Now, this looks good to me.

**Pull request merged**
