### PR TITLE
Add requested-ta-list and unneeded-ta-list

### LINKED ISSUE #2: Requested Components
Moved this issue from https://github.com/ietf-teep/architecture/issues/107 to the teep-protocol document.

Hannes raised the issue:

> ```
> Requested Components: A list of zero or more components (TAs or
> other dependencies needed by a TEE) that are requested by some
> depending app, but which are not currently installed in the TEE.
> ```
> How does this information carried inside the attestation payload relate to the info conveyed in the TEEP protocol?

Dave responded:
> As written, it implies that the list of components needed (but not already installed) are conveyed in the TEEP protocol inside claims. If we move them outside of claims then this bullet can be removed. We just need to pick one way.

Ming commented:

> This is a quite generic statement, and vague.
> 1. What other components beyond TAs will it contain and how will they be interpreted?
> 2. What the word "app" means by "depending app"? It can be Untrusted App or TA.
> 3. "needed by a TEE" - this isn't dependency of manifest file for dependent TAs by a TA in WG discussion. So this list of "components" needed by a TEE should have some examples to illustrate if they are not TAs needed by a requestTA call in the doc.
> 
> For device attestation, the device and TEE identifying information look to be right. This can be out of the list, or optional at most.
> 
> Question here: how about list of current TAs that have been installed in the TEE? I think it is meaningful in architecture doc to say what kind of information to present. Protocol doc has the actual way to carry them.

### LINKED ISSUE #5: Example of Device has the TA binary and just needs the metadata
Feedback from the SECIoT hackathon in Berlin,

We would like to have both scenarios in TEEP protocol in QueryRequest.
(a) The device has the TA binary and just needs the metadata (as for install or delete)
(b) The device needs both the TA binary and the metadata

The current prototype only using (b) at the moment.

This discussion was raised on otrp 
https://github.com/ietf-teep/OTrP/issues/2

### LINKED ISSUE #16: Delete wish from Client App to TAM
This is from the https://github.com/ietf-teep/otrp-over-http/issues/8.

Would like to add member of informing insert or delete wish in the QueryResponse which is sent from Device to TAM.

For the situation that  Client App is installed at the Device would like to have the TA associated it from the authorized TAM.

QueryResponse = {
 // adding optional member
      ? request : uint
}

while the 
requests = [ + ( 
    install /
    delete /
)]

and use the TA_LIST for specifying the TA which Client App would like to install or delete.

### PR DESCRIPTION
**Pull request by dthaler**
Fixes #2 
Fixes #5 
Fixes #16

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
The key question for this PR is whether the information should be in the query-response message, or inside the attestation evidence (the eat).  The last bullet of https://tools.ietf.org/html/draft-ietf-teep-architecture-12#section-7.1 currently implies it should be inside the evidence, but that may or may not be best.

Per a separate TEEP protocol issue to be filed (originally raised by Kathleen Moriarty) is the desire for evidence formats other than EAT to be used (but EAT may still be used as the attestation result format).   Putting the list in the query-response message allows it to be independent of evidence format and usable with any evidence format, including legacy proprietary ones that do not have a way to encode requested-ta-list.

Hence this PR, which if accepted may also need a corresponding change to the aforementioned section of the TEEP architecture.

**Comment by dthaler** [comment]
If PR #53 is merged first, this PR will be updated to reference ta-info instead of using bstr

**Review by mingpeiwk — APPROVED** [review]

**Review by mingpeiwk — APPROVED** [review]

**Review by mingpeiwk — COMMENTED** [review]
Shouldn't this 

   requested-ta-list  => [ + bstr ]

be also changed to refer to type requested-ta-info?

   requested-ta-list  => [ + requested-ta-info ]

The other PR used the similar reference in changing for ta-list.

**Comment by dthaler** [comment]
> Shouldn't this
> 
> requested-ta-list => [ + bstr ]
> 
> be also changed to refer to type requested-ta-info?

Yes, fixed, thanks for catching.

**Comment by dthaler** [comment]
Merging per Ming's approval and no other comments after 13 days

**Pull request merged**
