### PR TITLE
Add beginnings of behavioral specification

### PR DESCRIPTION
**Pull request by dthaler**
Addresses issue #81

Also adds a TODO where issue #43 resolution would affect text
(possibly among other places)

### CODE REVIEW

**Comment by dthaler** [comment]
@mcd500 please review

**Comment by mcd500** [comment]
This PR is based on top of the changes in TEEP Architecture draft with the https://github.com/ietf-teep/architecture/pull/216 to have  `UnrequestTA` API.
Wait for a little more of the PR to be merged at the TEEP Architecture.

**Comment by dthaler** [comment]
@mcd500 @hannestschofenig @mingpeiwk I've now updated this PR based on the conclusion of the UnrequestTA API and the Install/Delete messages being combined into Update.   I believe this is ready to be merged now, please review.

**Comment by mcd500** [comment]
@dthaler thanks merged

**Pull request merged**
