### PR TITLE
Update suit cose profiles

### PR DESCRIPTION
**Pull request by dthaler**
Addresses #356

@kentakayama please review and advise if this is not correct.

### CODE REVIEW

**Comment by hannestschofenig** [comment]
We should not use CTR mode in TEEP because the algorithm is really only needed in the case of firmware updates on IoT devices with flash memory, as explained in the SUIT firmware encryption draft.

Hence, I would not make this change.

**Comment by mingpeiwk** [comment]
In my reading of #356, it sounds that two CTRs (suit-sha256-*-ecdh-a128ctr) are the only two algorithms defined when it replaced "gcm" encryption mode? If we need to stay with "gcm", shall we ask for the ["mti" spec](https://datatracker.ietf.org/doc/draft-ietf-suit-mti/) to list both gcm and ctr as mandatory support? Thanks.

**Comment by dthaler** [comment]
suit-mti was updated to have 4 "current" profiles.  Per discussion with Hannes at hackathon 118, I updated this PR to list all 4 as mandatory for the TAM, and available for the TEEP agent to choose from.

**Review by mcd500 — APPROVED** [review]

**Comment by dthaler** [comment]
Discussed with Hannes, Akira, and Isobe-san

**Pull request merged**
