### PR TITLE
Use token for Passport model attestation nonce

### PR DESCRIPTION
**Pull request by dthaler**
Addresses issue #324

### CODE REVIEW

**Comment by dthaler** [comment]
@kentakayama please review

**Comment by kentakayama** [comment]
@dthaler 
Fine for me. It solves my issue.

I will make some supplement comments on this issue for the future readers.

**Comment by mcd500** [comment]
Merging.

**Comment by kentakayama** [comment]
@dthaler @mcd500 
These are my comprehension, and why I'm thinking this PR solved #324 .
Am I correct?

# Passport model + EAT Nonce
With this model the TAM request the freshness of the Attestation Result. The TAM MAY provide **token** in the QueryRequest message, and the eat_nonce claim in Attestation Result in QueryResponse MUST have the same value.

```mermaid
sequenceDiagram
TAM->>Agent: QueryRequest( { token: token } )
Agent-->>Verifier: Evidence
Verifier-->>Agent: Attestation Result( { eat_nonce: token } )
Agent->>TAM: QueryResponse( { token: token, attestation-payload: Attestation Result( { eat_nonce: token } ) } )
```

solid arrow: TEEP Protocol messages
dotted arrow: Out of TEEP Protocol

# Background Check model + EAT Nonce
With this model the Verifier behind the TAM MAY requests the freshness of the Evidence, and the TAM requests the freshness of the Attestation Result. The way to create Evidence is not specified in this document, but it SHOULD use the **challenge** value in the QueryRequest message. The eat_nonce claim in the Attestation Result created by the Verifier MUST have the same value as the challenge.

```mermaid
sequenceDiagram
Verifier-->>TAM: (Verifier's nonce)
TAM->>Agent: QueryRequest( { challenge: challenge } )
Agent->>TAM: QueryResponse( { attestation-payload: Evidence } )
TAM-->>Verifier: Evidence
Verifier-->>TAM: Attestation Result( { eat_nonce: challenge } )
```

# Hybrid model + EAT Nonce
There are 2 or more Verifiers. For example, one Verifier (Verifier-A) behind the Device and one Verifier (Verifier-B) behind the TAM.
With this case the model is like Background Check for the TAM, and is like Passport model for the Device.
The TAM MAY provide **challenge** in the QueryRequest, and then the eat_nonce claim in the Attestation Result created by Verifier-B MUST have the same value as the challenge.

```mermaid
sequenceDiagram
Verifier-B-->>TAM: (Verifier-B's nonce)
TAM->>Agent: QueryRequest( { challenge: challenge } )
Agent-->>Verifier-A: Evidence-A
Verifier-A-->>Agent: Attestation Result-A
Agent->>TAM: QueryResponse( { attestation-payload: Attestation Result-A as Evidence } )
TAM-->>Verifier-B: Evidence
Verifier-B-->>TAM: Attestation Result-B( { eat_nonce: challenge } )
```

**Comment by dthaler** [comment]
> @dthaler @mcd500 These are my comprehension, and why I'm thinking this PR solved #324 . Am I correct?

I believe so, yes.

**Pull request merged**
