### PR TITLE
s/bit is clear/bit is cleared

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

**Review by dthaler — APPROVED** [review]
Ok either way to me, no objection.

**Comment by dthaler** [comment]
Actually I dislike this change.  I just asked Bing Chat for its opinion:
> Q: which is more grammatically correct in a computing context. "the bit is clear" or "the bit is cleared"?
> A: In computing, the phrase “the bit is clear” is more grammatically correct than “the bit is cleared”. The word “clear” is used as an adjective to describe the state of the bit, which means that it is not set or has a value of 0. The word “cleared”, on the other hand, is used as a verb to describe the action of setting the bit to 0.

**Review by dthaler — CHANGES_REQUESTED** [review]
Grammar checker says current text is more correct.

**Comment by mingpeiwk** [comment]
Considering the ambiguity of the word "clear" vs "cleared", how about we use an alternative word that is more direct? How about "not set"?

In the prior slide 18 of https://datatracker.ietf.org/meeting/110/materials/slides-110-teep-teep-protocol-00, it has an informal statement about when the token isn't needed. The condition word is "is set".

"The token is not needed when the attestation bit is set in the data-item-requested value."

**Comment by hannestschofenig** [comment]
I closed this PR since my proposal was not accepted.

**Pull request closed without merging**
