### PR TITLE
Specify how TA_ID is used

### LINKED ISSUE #4: ta_id: does teep-device have to match all members to
We are in the middle of prototyping the teep over http.

The current draft specifies the `ta_id` with three members.
 
https://github.com/ietf-teep/teep-protocol/blob/master/draft-ietf-teep-protocol.xml#L327

At our initial protyping we are matching all three strings when tam received the requested ta from the teep-broker.
```
Vendor_ID=ietf-teep-wg
Class_ID=uuid or ta-name
Device_ID=teep-device
```

We are not sure matching all three member all the time is the expected behaviour, since ta-name or uuid matters most of the time.

Any recommendation is helpful for us.

Or Vender_ID and Device_ID are expected as only information only?

### PR DESCRIPTION
**Pull request by dthaler**
Fixes #4

Signed-off-by: Dave Thaler <dthaler@ntdev.microsoft.com>

### CODE REVIEW

**Review by mingpeiwk — COMMENTED** [review]
Should the second field for ta-info be optional -  ta-manifest-sequence-number: uint?

**Comment by dthaler** [comment]
> Should the second field for ta-info be optional - ta-manifest-sequence-number: uint?

I agree, now updated.

**Comment by dthaler** [comment]
Hannes reports that the SUIT component id is not a unique identifier, and we may need something else in the SUIT manifest to reference as a unique identifier

**Review by mingpeiwk — APPROVED** [review]

**Comment by dthaler** [comment]
Merging per Ming's approval so we can post the draft.  Any issues should be filed as new issues, or treated as part of ongoing Issue #70 which this PR will not resolve.

**Pull request merged**
